import { format } from 'date-fns';

export interface ReceiptPatient {
  nrNumber: string;
  fullName: string;
  gender?: string;
  mobile?: string | null;
  cnic?: string | null;
  registeredAt?: string;
  visitType?: string;
  departmentInfo?: { name?: string } | null;
  attendingDoctor?: { fullName?: string } | null;
}

/**
 * Print a patient registration receipt using the shared A4 receipt pattern.
 * Only fields that actually have a value are rendered, so the grid has no gaps.
 */
export function printPatientReceipt(patient: ReceiptPatient, hospitalName: string) {
  const infoFields: { label: string; value?: string | null }[] = [
    { label: 'MRN', value: patient.nrNumber },
    { label: 'Full Name', value: patient.fullName },
    { label: 'Gender', value: patient.gender },
    { label: 'Mobile', value: patient.mobile },
    { label: 'CNIC', value: patient.cnic },
    {
      label: 'Registered',
      value: patient.registeredAt
        ? format(new Date(patient.registeredAt), 'dd/MM/yyyy')
        : '',
    },
    { label: 'Visit Type', value: patient.visitType },
    { label: 'Department', value: patient.departmentInfo?.name },
    { label: 'Attending Doctor', value: patient.attendingDoctor?.fullName },
  ];

  const infoCells = infoFields
    .filter((f) => f.value && String(f.value).trim() !== '')
    .map(
      (f) =>
        `<div><div class="label">${f.label}</div><div class="value">${f.value}</div></div>`,
    )
    .join('');

  const receiptHTML = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Patient Details - ${patient.nrNumber}</title>
        <style>
          @page { size: A4; margin: 15mm 15mm 15mm 22mm; }
          * { box-sizing: border-box; }
          body { font-family: Arial, sans-serif; color: #111827; }
          h1, h2 { margin: 0 0 8px 0; }
          .header { border-bottom: 2px solid #111827; padding-bottom: 8px; margin-bottom: 16px; }
          .meta { font-size: 12px; color: #374151; }
          .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 16px; }
          .label { font-size: 13px; color: #6b7280; margin-bottom: 4px; }
          .value { font-size: 15px; font-weight: 600; }
          .footer { margin-top: 16px; font-size: 10px; color: #6b7280; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${hospitalName}</h1>
          <div class="meta">Printed: ${format(new Date(), 'dd/MM/yyyy hh:mm a')}</div>
        </div>

        <h2>Patient Information</h2>
        <div class="grid">
          ${infoCells}
        </div>

        <div class="footer">Generated by M-IMS</div>
      </body>
    </html>
  `;

  const printFrame = document.createElement('iframe');
  printFrame.style.cssText =
    'position:fixed;right:0;bottom:0;width:0;height:0;border:none;';
  document.body.appendChild(printFrame);

  const frameDoc = printFrame.contentWindow?.document;
  if (frameDoc) {
    frameDoc.open();
    frameDoc.write(receiptHTML);
    frameDoc.close();

    printFrame.onload = () => {
      setTimeout(() => {
        printFrame.contentWindow?.print();
        setTimeout(() => {
          document.body.removeChild(printFrame);
        }, 100);
      }, 250);
    };
  }
}
