events { worker_connections 1024; }
http {
    upstream backend { server 127.0.0.1:3001; }
    upstream frontend { server 127.0.0.1:3000; }
    
    server {
        listen 80;
        server_name localhost;
        
        location /api/ { proxy_pass http://backend; }
        location / { proxy_pass http://frontend; }
    }
}
